service: cake-ordering-system
frameworkVersion: '2'

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource:
            arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/ordersTable
        - Effect: Allow
          Action:
            - kinesis:PutRecord
          Resource:
            arn:aws:kinesis:${aws:region}:${aws:accountId}:stream/order-events
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource:
            - '*'
          Condition:
            StringEquals:
              ses:FromAddress:
                - cakeordermail@grr.la
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - arn:aws:sqs:${aws:region}:${aws:accountId}:deliveryServiceQueue
            - arn:aws:sqs:${aws:region}:${aws:accountId}:customerServiceQueue

functions:
  createOrder:
    handler: handler.createOrder
    events:
      - http:
          path: /order
          method: post
    environment:
      ORDER_TABLE_NAME: ordersTable
      ORDER_STREAM_NAME: order-events
  orderFulfilled:
    handler: handler.orderFulfilled
    events:
      - http:
          path: /order/fulfilled
          method: post
    environment:
      ORDER_TABLE_NAME: ordersTable
      ORDER_STREAM_NAME: order-events
  orderDelivered:
    handler: handler.orderDelivered
    events:
      - http:
          path: /order/delivered
          method: post
    environment:
      REGION: ${aws:region}
      ORDER_TABLE_NAME: ordersTable
      CUSTOMER_SERVICE_QUEUE:
        Ref: customerServiceQueue
  notifySuppliers:
    handler: handler.notifySuppliers
    events:
      - stream:
          arn: arn:aws:kinesis:${aws:region}:${aws:accountId}:stream/order-events
    environment:
      REGION: ${aws:region}
      CAKE_PRODUCER_EMAIL: orderservicemail@grr.la
      CAKE_ORDER_EMAIL: cakeordermail@grr.la
      ORDER_TABLE_NAME: ordersTable
      DELIVERY_COMPANY_QUEUE:
        Ref: deliveryServiceQueue
  notifyDeliveryCompany:
    handler: handler.notifyDeliveryCompany
    events:
      - sqs:
          arn: arn:aws:sqs:${aws:region}:${aws:accountId}:deliveryServiceQueue
          batchSize: 1
  notifyCustomerService:
    handler: handler.notifyCustomerService
    events:
      - sqs:
          arn: arn:aws:sqs:${aws:region}:${aws:accountId}:customerServiceQueue
          batchSize: 1

resources:
  Resources:
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1
    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ordersTable
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    deliveryServiceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: deliveryServiceQueue
    customerServiceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: customerServiceQueue
